version: "2"

run:
  timeout: 5m

linters:
  default: all
  disable:
    - dupl
    - mnd
    - gochecknoinits
    - gochecknoglobals
    - err113
    - wrapcheck
    - paralleltest
    - exhaustruct
    - wsl
    - gomodguard
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 30
    cyclop:
      max-complexity: 30
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/davecgh/go-spew/spew
              desc: spew is not allowed
    misspell:
      locale: US
    lll:
      line-length: 200
    funlen:
      lines: 500
      statements: 500
    gocognit:
      min-complexity: 80
    prealloc:
      for-loops: true
  exclusions:
    paths:
      - vendor
